filter:
    excluded_paths:
        - '*/test/*'
        - '*/migrations/*'

checks:
    python:
        code_rating: true
        duplicate_code: true

build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
                  tests:
                    override:
                      - command: './run-tests.sh'
                        coverage:
                          file: '.coverage'
                          config_file: '.coveragerc'
                          format: 'py-cc'
