filter:
    excluded_paths:
        - '*/test/*'
        - '*/migrations/*'

checks:
    python:
        code_rating: true
        duplicate_code: true


build:
    nodes:
        coverage:
          tests:
            override:
              - command: 'python manage.py test'
                coverage:
                  file: '.coverage'
                  config_file: '.coveragerc'
                  format: 'py-cc'
        analysis:
            project_setup:
                override: true
            tests:
                override: [py-scrutinizer-run]
