# Generated by Django 3.2.7 on 2021-10-04 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('social_security_nr', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('tel_nr', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('belong_to_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('vaccin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vaccin_name', models.CharField(max_length=255)),
                ('protects_against', models.CharField(max_length=255)),
                ('info_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dose_nr', models.IntegerField()),
                ('date_of_vaccination', models.DateField()),
                ('date_of_next_vaccination', models.DateField()),
                ('vaccination_done', models.CharField(default='NULL', max_length=10)),
                ('note', models.CharField(default='NULL', max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='vaccinationmanagement.patient')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccin', to='vaccinationmanagement.vaccin')),
            ],
        ),
    ]
