# Generated by Django 3.2.7 on 2021-09-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('social_security_nr', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('tel_nr', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccin',
            fields=[
                ('vaccin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vaccin_name', models.CharField(max_length=255)),
                ('protects_against', models.CharField(max_length=255)),
                ('info_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_vaccination', models.DateField()),
                ('date_of_next_vaccination', models.DateField()),
                ('note', models.CharField(max_length=255)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccinationmanagement.patient')),
                ('vaccin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccinationmanagement.vaccin')),
            ],
        ),
    ]
