# Generated by Django 3.2.7 on 2021-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='vaccination_done',
            field=models.BooleanField(),
        ),
    ]
