# Generated by Django 3.2.7 on 2021-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccin',
            name='vaccin_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccination_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
