# Generated by Django 3.2.7 on 2021-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationmanagement', '0003_alter_vaccination_date_of_next_vaccination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='date_of_next_vaccination',
            field=models.DateField(default='NULL', null=True),
        ),
    ]
